using System.ComponentModel.DataAnnotations;

namespace HealthBridge.Api.DTOs.Appointments;

/// <summary>Request DTO for the AI doctor-recommendation endpoint.</summary>
public class DoctorRecommendationRequestDto
{
    [Required(ErrorMessage = "Symptoms are required.")]
    [MinLength(3, ErrorMessage = "Please describe your symptoms in 2 or more words (e.g., 'frequent headache' or 'persistent cough').")]
    [MaxLength(500, ErrorMessage = "Symptom description must not exceed 500 characters.")]
    public string Symptoms { get; set; } = string.Empty;
}

/// <summary>Response DTO returned by POST /api/appointments/recommend-doctor.</summary>
public class DoctorRecommendationResponseDto
{
    /// <summary>Unique workflow ID for audit tracing.</summary>
    public Guid WorkflowId { get; set; }

    /// <summary>
    /// One of: RECOMMENDATION_READY | NEED_MORE_CONTEXT | SAFETY_ESCALATION | INPUT_INVALID | SAFE_FAILURE
    /// </summary>
    public string Status { get; set; } = string.Empty;

    /// <summary>Recommended specialty (only present when Status == RECOMMENDATION_READY).</summary>
    public string? Specialty { get; set; }

    /// <summary>Confidence score 0–1 (only present when Status == RECOMMENDATION_READY).</summary>
    public double? Confidence { get; set; }

    /// <summary>One or two plain-language sentences explaining the suggestion (never a diagnosis).</summary>
    public string? Reason { get; set; }

    /// <summary>Targeted follow-up questions (only when Status == NEED_MORE_CONTEXT).</summary>
    public List<string> FollowUpQuestions { get; set; } = new();

    /// <summary>Safety message to show prominently (only when Status == SAFETY_ESCALATION).</summary>
    public string? SafetyMessage { get; set; }

    /// <summary>Machine-readable red-flag classification code (e.g., CARDIAC, STROKE, UNCONSCIOUS).</summary>
    public string? RedFlagCode { get; set; }

    /// <summary>Structured execution plan generated by the Coordinator Agent.</summary>
    public List<string> ExecutionPlan { get; set; } = new();

    /// <summary>Auditable trace of steps executed across specialized agents.</summary>
    public List<AgentStepLogDto> StepLogs { get; set; } = new();

    /// <summary>Doctors matched and ranked by the DoctorSlotAllocation tool agent.</summary>
    public List<MatchedDoctorDto> MatchedDoctors { get; set; } = new();

    /// <summary>Human-in-the-Loop status: PENDING_APPROVAL | APPROVED | REJECTED | NOT_REQUIRED.</summary>
    public string ApprovalStatus { get; set; } = "NOT_REQUIRED";

    /// <summary>Total workflow execution latency in milliseconds.</summary>
    public long TotalDurationMs { get; set; }
}

public class MatchedDoctorDto
{
    public int DoctorId { get; set; }
    public string FullName { get; set; } = string.Empty;
    public string Specialization { get; set; } = string.Empty;
    public string Qualifications { get; set; } = string.Empty;
    public string HospitalBranch { get; set; } = string.Empty;
    public string RoomNumber { get; set; } = string.Empty;
    public decimal ConsultationFee { get; set; }
    public int ExperienceYears { get; set; }
    public double Rating { get; set; }
    public string MatchReason { get; set; } = string.Empty;
    public int? NextSessionId { get; set; }
    public string? NextSessionDate { get; set; }
    public string? NextSessionTime { get; set; }
    public int AvailableSlots { get; set; }
}

public class AgentStepLogDto
{
    public string AgentName { get; set; } = string.Empty;
    public string Action { get; set; } = string.Empty;
    public string? StepName { get; set; }
    public string? Input { get; set; }
    public string? Output { get; set; }
    public string Status { get; set; } = "COMPLETED"; // COMPLETED | WAITING_FOR_APPROVAL | BLOCKED | ESCALATED | INSUFFICIENT_CONTEXT
    public bool Success { get; set; } = true;
    public string? ToolCalled { get; set; }
    public string? RedFlagCode { get; set; }
    public string? MatchedCategory { get; set; }
    public long DurationMs { get; set; }
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;
}

public class ApproveRecommendationRequestDto
{
    public int? SelectedDoctorId { get; set; }
    public int? SelectedSessionId { get; set; }
    public string? Notes { get; set; }
}

public class RejectRecommendationRequestDto
{
    public string? Notes { get; set; }
}

/// <summary>Internal Gemini response shape.</summary>
public class GeminiTriageResult
{
    public string? Status { get; set; }
    public string? Specialty { get; set; }
    public double Confidence { get; set; }
    public string? Reason { get; set; }
    public List<string>? FollowUpQuestions { get; set; }
}
