// <auto-generated />
using System;
using LabManagement.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LabManagement.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910031442_AddEMRModule")]
    partial class AddEMRModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LabManagement.API.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("LabManagement.API.Models.EMR.ConsultationNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClinicalNotes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ConsultationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorDesignation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DoctorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrescribedMedicines")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecommendedTests")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationDate");

                    b.HasIndex("PatientCode");

                    b.HasIndex("PatientId");

                    b.ToTable("ConsultationNotes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            ClinicalNotes = "Patient presented with mild morning headaches and recorded BP 142/92 mmHg over 3 consecutive clinic visits. Denies chest pain, palpitation, or dyspnea. Advised DASH diet, sodium restriction < 2g/day, and routine aerobic exercise. Follow-up in 4 weeks.",
                            ConsultationDate = new DateTime(2026, 8, 10, 10, 30, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 8, 10, 11, 0, 0, 0, DateTimeKind.Utc),
                            Diagnosis = "Stage 1 Essential Hypertension with sinus rhythm",
                            DoctorDesignation = "Senior Consultant Cardiologist",
                            DoctorId = "DOC-101",
                            DoctorName = "Dr. Sarah Chen",
                            PatientCode = "PAT-1001",
                            PatientId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PrescribedMedicines = "[{\"name\":\"Lisinopril\",\"dosage\":\"10mg once daily in morning\",\"duration\":\"30 Days\"},{\"name\":\"Amlodipine\",\"dosage\":\"5mg once daily\",\"duration\":\"30 Days\"}]",
                            RecommendedTests = "Complete Blood Count (CBC), Lipid Panel, Resting ECG",
                            Status = "Completed",
                            UpdatedAt = new DateTime(2026, 8, 10, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            ClinicalNotes = "Occasional nocturnal dry cough following high pollen exposure. Spirometry showed FEV1 84% predicted, fully responsive to bronchodilators. Avoid known triggers.",
                            ConsultationDate = new DateTime(2026, 7, 18, 14, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2026, 7, 18, 14, 30, 0, 0, DateTimeKind.Utc),
                            Diagnosis = "Mild Seasonal Allergic Asthma exacerbation",
                            DoctorDesignation = "Consultant Pulmonologist",
                            DoctorId = "DOC-102",
                            DoctorName = "Dr. Michael Chang",
                            PatientCode = "PAT-1001",
                            PatientId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PrescribedMedicines = "[{\"name\":\"Salbutamol (Ventolin) Inhaler\",\"dosage\":\"2 puffs as needed for wheeze\",\"duration\":\"As needed\"}]",
                            RecommendedTests = "Chest X-Ray, Total Serum IgE",
                            Status = "Completed",
                            UpdatedAt = new DateTime(2026, 7, 18, 14, 30, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LabManagement.API.Models.EMR.EMRAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("Timestamp");

                    b.ToTable("EMRAuditLogs");
                });

            modelBuilder.Entity("LabManagement.API.Models.EMR.LabReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<string>("OrderedDoctor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResultsSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TestTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PatientCode");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("LabReports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Category = "Haematology",
                            CreatedAt = new DateTime(2026, 8, 11, 9, 30, 0, 0, DateTimeKind.Utc),
                            FileName = "CBC_Report_PAT1001.pdf",
                            FileUrl = "/uploads/reports/CBC_PAT1001.pdf",
                            OrderedDoctor = "Dr. Sarah Chen",
                            PatientCode = "PAT-1001",
                            PatientId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ReportDate = new DateTime(2026, 8, 11, 9, 15, 0, 0, DateTimeKind.Utc),
                            ResultsSummary = "WBC: 6.8 x10^3/uL (Normal), RBC: 4.9 x10^6/uL, Hemoglobin: 14.8 g/dL, Platelets: 240 x10^3/uL. Indices within normal physiological limits.",
                            Status = "Completed",
                            TestTitle = "Complete Blood Count (CBC)",
                            UpdatedAt = new DateTime(2026, 8, 11, 9, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            Category = "Biochemistry",
                            CreatedAt = new DateTime(2026, 8, 11, 9, 45, 0, 0, DateTimeKind.Utc),
                            FileName = "Lipid_Profile_PAT1001.pdf",
                            FileUrl = "/uploads/reports/Lipid_PAT1001.pdf",
                            OrderedDoctor = "Dr. Sarah Chen",
                            PatientCode = "PAT-1001",
                            PatientId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ReportDate = new DateTime(2026, 8, 11, 9, 20, 0, 0, DateTimeKind.Utc),
                            ResultsSummary = "Total Cholesterol: 185 mg/dL (Normal < 200), HDL: 48 mg/dL, LDL: 112 mg/dL, Triglycerides: 125 mg/dL.",
                            Status = "Completed",
                            TestTitle = "Fasting Lipid Profile",
                            UpdatedAt = new DateTime(2026, 8, 11, 9, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-333333333333"),
                            Category = "Cardiology",
                            CreatedAt = new DateTime(2026, 8, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            OrderedDoctor = "Dr. Sarah Chen",
                            PatientCode = "PAT-1001",
                            PatientId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            ReportDate = new DateTime(2026, 8, 15, 11, 0, 0, 0, DateTimeKind.Utc),
                            ResultsSummary = "Specimen collected; awaiting cardiologist interpretation signature.",
                            Status = "Pending",
                            TestTitle = "Resting 12-Lead Electrocardiogram (ECG)",
                            UpdatedAt = new DateTime(2026, 8, 15, 11, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LabManagement.API.Models.EMR.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Allergies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ChronicConditions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmergencyContactPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PatientCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("PatientCode")
                        .IsUnique();

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-111111111111"),
                            Address = "742 Evergreen Terrace, Springfield",
                            Allergies = "Penicillin, Peanuts",
                            BloodGroup = "O+",
                            ChronicConditions = "Stage 1 Hypertension, Mild Asthma",
                            ContactPhone = "+1 555-0192",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1985, 5, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john.anderson@example.com",
                            EmergencyContactName = "Mary Anderson (Spouse)",
                            EmergencyContactPhone = "+1 555-0193",
                            FullName = "John Anderson",
                            Gender = "Male",
                            PatientCode = "PAT-1001",
                            UpdatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a2222222-2222-2222-2222-222222222222"),
                            Address = "120 Elm Street, Dallas",
                            Allergies = "Sulfa antibiotics",
                            BloodGroup = "A+",
                            ChronicConditions = "Type 2 Diabetes Mellitus",
                            ContactPhone = "+1 555-0284",
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1992, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria.garcia@example.com",
                            EmergencyContactName = "Carlos Garcia (Brother)",
                            EmergencyContactPhone = "+1 555-0285",
                            FullName = "Maria Garcia",
                            Gender = "Female",
                            PatientCode = "PAT-1002",
                            UpdatedAt = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a3333333-3333-3333-3333-333333333333"),
                            Address = "88 Pine Avenue, Seattle",
                            Allergies = "None reported",
                            BloodGroup = "B+",
                            ChronicConditions = "Hyperlipidemia",
                            ContactPhone = "+1 555-0371",
                            CreatedAt = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1968, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "robert.kim@example.com",
                            EmergencyContactName = "Susan Kim (Daughter)",
                            EmergencyContactPhone = "+1 555-0372",
                            FullName = "Robert Kim",
                            Gender = "Male",
                            PatientCode = "PAT-1003",
                            UpdatedAt = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LabManagement.API.Models.EMR.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatientCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrescribedDoctor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PatientCode");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 8, 10, 11, 15, 0, 0, DateTimeKind.Utc),
                            Dosage = "Take 1 tablet by mouth daily in the morning with water",
                            Duration = "30 Days",
                            EndDate = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            MedicationName = "Lisinopril 10mg",
                            PatientCode = "PAT-1001",
                            PatientId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PrescribedDoctor = "Dr. Sarah Chen",
                            StartDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UnitPrice = 12.50m,
                            UpdatedAt = new DateTime(2026, 8, 10, 11, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 8, 10, 11, 15, 0, 0, DateTimeKind.Utc),
                            Dosage = "Take 1 tablet daily with or without food",
                            Duration = "30 Days",
                            EndDate = new DateTime(2026, 9, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            MedicationName = "Amlodipine 5mg",
                            PatientCode = "PAT-1001",
                            PatientId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PrescribedDoctor = "Dr. Sarah Chen",
                            StartDate = new DateTime(2026, 8, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UnitPrice = 10.00m,
                            UpdatedAt = new DateTime(2026, 8, 10, 11, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("d3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 6, 1, 15, 0, 0, 0, DateTimeKind.Utc),
                            Dosage = "Take 1 capsule every 8 hours for 7 days",
                            Duration = "7 Days",
                            EndDate = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            MedicationName = "Amoxicillin 500mg",
                            PatientCode = "PAT-1001",
                            PatientId = new Guid("a1111111-1111-1111-1111-111111111111"),
                            PrescribedDoctor = "Dr. Michael Chang",
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Completed",
                            UnitPrice = 15.00m,
                            UpdatedAt = new DateTime(2026, 6, 8, 15, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("LabManagement.API.Models.LabBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AIConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<string>("AIExtractedDoctorName")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("AIPrescriptionDate")
                        .HasColumnType("date");

                    b.Property<string>("AIVerification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AIVerificationNotes")
                        .HasColumnType("text");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LabTestId")
                        .HasColumnType("uuid");

                    b.Property<string>("PatientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrescriptionImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ResultFileUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResultsUploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<string>("TechnicianNotes")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("TimeSlot")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LabTestId");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("LabBookings");
                });

            modelBuilder.Entity("LabManagement.API.Models.LabTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TurnaroundDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("LabTests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = "Haematology",
                            CreatedAt = new DateTime(2026, 9, 10, 3, 14, 39, 829, DateTimeKind.Utc).AddTicks(2627),
                            Description = "Measures different components of blood including red/white cells and platelets.",
                            IsActive = true,
                            IsRestricted = false,
                            Name = "Complete Blood Count (CBC)",
                            Price = 1500m,
                            TurnaroundDays = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "Biochemistry",
                            CreatedAt = new DateTime(2026, 9, 10, 3, 14, 39, 829, DateTimeKind.Utc).AddTicks(2710),
                            Description = "Measures cholesterol and triglyceride levels in the blood.",
                            IsActive = true,
                            IsRestricted = true,
                            Name = "Lipid Panel",
                            Price = 2500m,
                            TurnaroundDays = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Category = "Biochemistry",
                            CreatedAt = new DateTime(2026, 9, 10, 3, 14, 39, 829, DateTimeKind.Utc).AddTicks(2718),
                            Description = "Measures blood sugar levels after an 8-hour fast.",
                            IsActive = true,
                            IsRestricted = false,
                            Name = "Blood Glucose Fasting",
                            Price = 500m,
                            TurnaroundDays = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Category = "Endocrinology",
                            CreatedAt = new DateTime(2026, 9, 10, 3, 14, 39, 829, DateTimeKind.Utc).AddTicks(2725),
                            Description = "Evaluates thyroid gland function (TSH, T3, T4).",
                            IsActive = true,
                            IsRestricted = true,
                            Name = "Thyroid Function Test (TFT)",
                            Price = 3500m,
                            TurnaroundDays = 2
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Category = "Microbiology",
                            CreatedAt = new DateTime(2026, 9, 10, 3, 14, 39, 829, DateTimeKind.Utc).AddTicks(2734),
                            Description = "Analyses physical, chemical and microscopic properties of urine.",
                            IsActive = true,
                            IsRestricted = false,
                            Name = "Urine Full Report (UFR)",
                            Price = 800m,
                            TurnaroundDays = 1
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Category = "Radiology",
                            CreatedAt = new DateTime(2026, 9, 10, 3, 14, 39, 829, DateTimeKind.Utc).AddTicks(2740),
                            Description = "Imaging of lungs, heart and chest wall.",
                            IsActive = true,
                            IsRestricted = true,
                            Name = "Chest X-Ray",
                            Price = 2000m,
                            TurnaroundDays = 1
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Category = "Biochemistry",
                            CreatedAt = new DateTime(2026, 9, 10, 3, 14, 39, 829, DateTimeKind.Utc).AddTicks(2748),
                            Description = "Assesses liver health via enzyme and protein levels.",
                            IsActive = true,
                            IsRestricted = true,
                            Name = "Liver Function Test (LFT)",
                            Price = 3000m,
                            TurnaroundDays = 2
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Category = "Haematology",
                            CreatedAt = new DateTime(2026, 9, 10, 3, 14, 39, 829, DateTimeKind.Utc).AddTicks(2766),
                            Description = "Detects inflammation in the body.",
                            IsActive = true,
                            IsRestricted = false,
                            Name = "ESR (Erythrocyte Sedimentation Rate)",
                            Price = 600m,
                            TurnaroundDays = 1
                        });
                });

            modelBuilder.Entity("LabManagement.API.Models.LabTimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentBookings")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Time")
                        .IsUnique();

                    b.ToTable("LabTimeSlots");
                });

            modelBuilder.Entity("LabManagement.API.Models.EMR.ConsultationNote", b =>
                {
                    b.HasOne("LabManagement.API.Models.EMR.Patient", "Patient")
                        .WithMany("ConsultationNotes")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("LabManagement.API.Models.EMR.LabReport", b =>
                {
                    b.HasOne("LabManagement.API.Models.EMR.Patient", "Patient")
                        .WithMany("LabReports")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("LabManagement.API.Models.EMR.Prescription", b =>
                {
                    b.HasOne("LabManagement.API.Models.EMR.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("LabManagement.API.Models.LabBooking", b =>
                {
                    b.HasOne("LabManagement.API.Models.LabTest", "LabTest")
                        .WithMany("Bookings")
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LabTest");
                });

            modelBuilder.Entity("LabManagement.API.Models.EMR.Patient", b =>
                {
                    b.Navigation("ConsultationNotes");

                    b.Navigation("LabReports");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("LabManagement.API.Models.LabTest", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
