// <auto-generated />
using System;
using LabManagement.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LabManagement.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LabManagement.API.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("LabManagement.API.Models.LabBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AIConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<string>("AIExtractedDoctorName")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("AIPrescriptionDate")
                        .HasColumnType("date");

                    b.Property<string>("AIVerification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AIVerificationNotes")
                        .HasColumnType("text");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LabTestId")
                        .HasColumnType("uuid");

                    b.Property<string>("PatientEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrescriptionImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ResultFileUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResultsUploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TechnicianId")
                        .HasColumnType("uuid");

                    b.Property<string>("TechnicianNotes")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("TimeSlot")
                        .HasColumnType("time without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LabTestId");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("LabBookings");
                });

            modelBuilder.Entity("LabManagement.API.Models.LabTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRestricted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TurnaroundDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Name");

                    b.ToTable("LabTests");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = "Haematology",
                            CreatedAt = new DateTime(2026, 8, 6, 10, 19, 18, 354, DateTimeKind.Utc).AddTicks(628),
                            Description = "Measures different components of blood including red/white cells and platelets.",
                            IsActive = true,
                            IsRestricted = false,
                            Name = "Complete Blood Count (CBC)",
                            Price = 1500m,
                            TurnaroundDays = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "Biochemistry",
                            CreatedAt = new DateTime(2026, 8, 6, 10, 19, 18, 354, DateTimeKind.Utc).AddTicks(646),
                            Description = "Measures cholesterol and triglyceride levels in the blood.",
                            IsActive = true,
                            IsRestricted = true,
                            Name = "Lipid Panel",
                            Price = 2500m,
                            TurnaroundDays = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Category = "Biochemistry",
                            CreatedAt = new DateTime(2026, 8, 6, 10, 19, 18, 354, DateTimeKind.Utc).AddTicks(649),
                            Description = "Measures blood sugar levels after an 8-hour fast.",
                            IsActive = true,
                            IsRestricted = false,
                            Name = "Blood Glucose Fasting",
                            Price = 500m,
                            TurnaroundDays = 1
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Category = "Endocrinology",
                            CreatedAt = new DateTime(2026, 8, 6, 10, 19, 18, 354, DateTimeKind.Utc).AddTicks(652),
                            Description = "Evaluates thyroid gland function (TSH, T3, T4).",
                            IsActive = true,
                            IsRestricted = true,
                            Name = "Thyroid Function Test (TFT)",
                            Price = 3500m,
                            TurnaroundDays = 2
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Category = "Microbiology",
                            CreatedAt = new DateTime(2026, 8, 6, 10, 19, 18, 354, DateTimeKind.Utc).AddTicks(664),
                            Description = "Analyses physical, chemical and microscopic properties of urine.",
                            IsActive = true,
                            IsRestricted = false,
                            Name = "Urine Full Report (UFR)",
                            Price = 800m,
                            TurnaroundDays = 1
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Category = "Radiology",
                            CreatedAt = new DateTime(2026, 8, 6, 10, 19, 18, 354, DateTimeKind.Utc).AddTicks(668),
                            Description = "Imaging of lungs, heart and chest wall.",
                            IsActive = true,
                            IsRestricted = true,
                            Name = "Chest X-Ray",
                            Price = 2000m,
                            TurnaroundDays = 1
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Category = "Biochemistry",
                            CreatedAt = new DateTime(2026, 8, 6, 10, 19, 18, 354, DateTimeKind.Utc).AddTicks(671),
                            Description = "Assesses liver health via enzyme and protein levels.",
                            IsActive = true,
                            IsRestricted = true,
                            Name = "Liver Function Test (LFT)",
                            Price = 3000m,
                            TurnaroundDays = 2
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Category = "Haematology",
                            CreatedAt = new DateTime(2026, 8, 6, 10, 19, 18, 354, DateTimeKind.Utc).AddTicks(674),
                            Description = "Detects inflammation in the body.",
                            IsActive = true,
                            IsRestricted = false,
                            Name = "ESR (Erythrocyte Sedimentation Rate)",
                            Price = 600m,
                            TurnaroundDays = 1
                        });
                });

            modelBuilder.Entity("LabManagement.API.Models.LabTimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentBookings")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Date", "Time")
                        .IsUnique();

                    b.ToTable("LabTimeSlots");
                });

            modelBuilder.Entity("LabManagement.API.Models.LabBooking", b =>
                {
                    b.HasOne("LabManagement.API.Models.LabTest", "LabTest")
                        .WithMany("Bookings")
                        .HasForeignKey("LabTestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LabTest");
                });

            modelBuilder.Entity("LabManagement.API.Models.LabTest", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
