using HealthBridge.Api.Data;
using HealthBridge.Api.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace HealthBridge.Api.Controllers.Pharmacy;

[ApiController]
[Route("api/[controller]")]
[IgnoreAntiforgeryToken]
public class AIForecastNotesController : ControllerBase
{
    private readonly ApplicationDbContext _context;
    private readonly ILogger<AIForecastNotesController> _logger;

    public AIForecastNotesController(ApplicationDbContext context, ILogger<AIForecastNotesController> logger)
    {
        _context = context;
        _logger = logger;
    }

    private async Task EnsureTableExistsAsync()
    {
        try
        {
            await _context.Database.ExecuteSqlRawAsync(@"
            CREATE TABLE IF NOT EXISTS ""AIForecastNotes"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""MedicineId"" integer NOT NULL,
                ""MedicineName"" text NOT NULL,
                ""Category"" text NOT NULL,
                ""UnitPrice"" numeric NOT NULL,
                ""CurrentStock"" integer NOT NULL,
                ""DaysUntilEmpty"" integer,
                ""AverageDailySales"" double precision NOT NULL,
                ""Trend"" text NOT NULL,
                ""StockStatus"" text NOT NULL,
                ""PredictedDemand7Days"" integer NOT NULL,
                ""PredictedDemand30Days"" integer NOT NULL,
                ""PredictedDemand60Days"" integer NOT NULL,
                ""PredictedDemand90Days"" integer NOT NULL,
                ""SeasonalFactor"" text,
                ""SeasonalMultiplier"" double precision NOT NULL,
                ""ProjectedRevenue30Days"" numeric NOT NULL,
                ""AtRiskRevenue"" numeric NOT NULL,
                ""ReorderPoint"" integer NOT NULL,
                ""SuggestedOrderQty"" integer NOT NULL,
                ""OrderByDate"" timestamp with time zone,
                ""AIInsight"" text,
                ""AIRecommendation"" text,
                ""Urgency"" text NOT NULL,
                ""Confidence"" double precision NOT NULL,
                ""TakenBy"" text NOT NULL,
                ""TakenAt"" timestamp with time zone NOT NULL,
                ""NoteStatus"" text NOT NULL
            );");
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "EnsureTableExistsAsync error (table may already exist)");
        }
    }

    [HttpGet]
    public async Task<ActionResult<IEnumerable<AIForecastNote>>> GetAll()
    {
        await EnsureTableExistsAsync();
        var notes = await _context.AIForecastNotes
            .OrderByDescending(n => n.TakenAt)
            .ToListAsync();
        return Ok(notes);
    }

    [HttpPost]
    public async Task<ActionResult<AIForecastNote>> Create([FromBody] AIForecastNote note)
    {
        await EnsureTableExistsAsync();
        note.TakenAt = DateTime.UtcNow;
        if (string.IsNullOrWhiteSpace(note.NoteStatus))
        {
            note.NoteStatus = "PENDING";
        }
        _context.AIForecastNotes.Add(note);
        await _context.SaveChangesAsync();
        return Ok(note);
    }

    [HttpPut("{id}")]
    public async Task<ActionResult<AIForecastNote>> UpdateStatus(int id, [FromBody] NoteStatusUpdateDto dto)
    {
        var note = await _context.AIForecastNotes.FindAsync(id);
        if (note == null) return NotFound();

        if (!string.IsNullOrWhiteSpace(dto.NoteStatus))
        {
            note.NoteStatus = dto.NoteStatus.ToUpper();
        }

        await _context.SaveChangesAsync();
        return Ok(note);
    }

    [HttpDelete("{id}")]
    public async Task<ActionResult> Delete(int id)
    {
        var note = await _context.AIForecastNotes.FindAsync(id);
        if (note == null) return NotFound();
        _context.AIForecastNotes.Remove(note);
        await _context.SaveChangesAsync();
        return NoContent();
    }

    [HttpDelete("clear-all")]
    public async Task<ActionResult> ClearAll()
    {
        var notes = await _context.AIForecastNotes.ToListAsync();
        _context.AIForecastNotes.RemoveRange(notes);
        await _context.SaveChangesAsync();
        return Ok(new { deleted = notes.Count });
    }
}

public class NoteStatusUpdateDto
{
    public string NoteStatus { get; set; } = "PENDING";
}
